[env:nucleo_h723zg]
platform = ststm32
board = nucleo_h723zg
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags = -DENCODER_USE_POLLING=0 -DENCODER_USE_TIM=1 -Wl,-u,_printf_float -DHSE_VALUE=8000000
